"""Generate wire models from our explicitly supported OpenAPI schema subset."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "packages/protocol/openapi.json"


def generate():
    api = json.loads(SCHEMA.read_text())
    schemas = api["components"]["schemas"]
    cs = ["// Generated by scripts/generate_protocol.py; do not edit.",
          "using System.Text.Json.Serialization;", "", "namespace PhoneTransfer.Protocol;", ""]
    kt = ["// Generated by scripts/generate_protocol.py; do not edit.",
          "package com.shinpstudio.phonetransfer.protocol", "",
          "import kotlinx.serialization.Serializable", ""]

    def kind(field, language):
        if "$ref" in field:
            name = field["$ref"].split("/")[-1]
            if name not in schemas:
                raise ValueError(f"Unresolved reference: {name}")
            return name
        t = field["type"]
        if t == "array":
            item = kind(field["items"], language)
            return f"IReadOnlyList<{item}>" if language == "cs" else f"List<{item}>"
        return {"string": ("string", "String"), "integer": ("long", "Long"),
                "boolean": ("bool", "Boolean")}[t][0 if language == "cs" else 1]

    for name, schema in schemas.items():
        if schema["type"] != "object" or set(schema["required"]) != set(schema["properties"]):
            raise ValueError("Generator only supports objects with required properties")
        fields = schema["properties"]
        cs.append(f"public sealed record {name}(")
        cs.append(",\n".join(f'    [property: JsonPropertyName("{key}")] {kind(value, "cs")} {key[0].upper() + key[1:]}'
                            for key, value in fields.items()) + ");")
        cs.append("")
        kt += ["@Serializable", f"data class {name}("]
        kt.extend(f"    val {key}: {kind(value, 'kt')}," for key, value in fields.items())
        kt += [")", ""]
    return {
        ROOT / "packages/protocol/dotnet/Generated/Models.g.cs": "\n".join(cs),
        ROOT / "packages/protocol/kotlin/src/main/kotlin/com/shinpstudio/phonetransfer/protocol/Models.kt": "\n".join(kt),
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, contents in generate().items():
        if args.check:
            if not path.exists() or path.read_text() != contents:
                raise SystemExit(f"Generated protocol is stale: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
