// Generated by scripts/generate_protocol.py; do not edit.
package com.shinpstudio.phonetransfer.protocol

import kotlinx.serialization.Serializable

@Serializable
data class ApiError(
    val code: String,
    val message: String,
    val retryable: Boolean,
    val requestId: String,
)

@Serializable
data class ServerInfo(
    val deviceId: String,
    val displayName: String,
    val appVersion: String,
    val buildNumber: Long,
    val protocolVersion: Long,
)

@Serializable
data class Share(
    val id: String,
    val name: String,
    val writable: Boolean,
)

@Serializable
data class ShareList(
    val items: List<Share>,
)

@Serializable
data class FileEntry(
    val name: String,
    val relativePath: String,
    val kind: String,
    val size: Long,
    val modifiedAt: String,
)

@Serializable
data class FileList(
    val items: List<FileEntry>,
    val nextCursor: String,
)

@Serializable
data class CreateTransfer(
    val shareId: String,
    val relativePath: String,
    val totalSize: Long,
    val sha256: String,
    val idempotencyKey: String,
)

@Serializable
data class Transfer(
    val transferId: String,
    val fileName: String,
    val totalSize: Long,
    val transferredBytes: Long,
    val sha256: String,
    val status: String,
    val updatedAt: String,
)

@Serializable
data class SendText(
    val kind: String,
    val content: String,
    val idempotencyKey: String,
)

@Serializable
data class TextEntry(
    val id: String,
    val kind: String,
    val content: String,
    val createdAt: String,
    val sourceDeviceId: String,
)

@Serializable
data class TextHistory(
    val items: List<TextEntry>,
    val nextCursor: String,
)

@Serializable
data class PairingQr(
    val protocolVersion: Long,
    val deviceId: String,
    val displayName: String,
    val endpoint: String,
    val serverSpkiSha256: String,
    val token: String,
    val expiresAt: String,
    val apiEndpoint: String,
)

@Serializable
data class PairingRequest(
    val deviceId: String,
    val displayName: String,
    val token: String,
    val certificateDer: String,
    val proofSignature: String,
)

@Serializable
data class PairingStatus(
    val requestId: String,
    val status: String,
)
